const lang = {
  de: {
    selectGame: "Spielesammlung",
    enterName: "Gib deinen Namen ein:",
    namePlaceholder: "Dein Name",
    nameError: "Bitte zuerst deinen Namen eingeben!",
    online: "Online spielen",
    vsComputer: "Gegen Computer",
    back: "← Zurück",
    gameSelection: "← Spielauswahl",
    startGame: "Spiel starten",
    createGame: "Spiel erstellen",
    loading: "Laden...",
    yourTurn: "Du bist dran",
    waitingOpponent: "Warte auf Mitspieler...",
    youWin: "Du gewinnst!",
    draw: "Unentschieden!",
    wins: "gewinnt!",
    rematch: "Rematch",
    newGame: "Neues Spiel",
    inviteFriend: "👉 Freund einladen:",
    copyLink: "Link kopieren",
    playAs: "Du spielst als",
    spectating: "Zuschauer...",
    confirmName: "Bestätigen",
    enterNameFirst: "Bitte gib deinen Namen ein:",
    // TicTacToe
    tictactoe: "Tic Tac Toe",
    tictactoeDesc: "3 in einer Reihe",
    // Connect Four
    connectFour: "Vier Gewinnt",
    connectFourDesc: "4 in einer Reihe",
    columnFull: "Spalte voll!",
    // RPS
    rps: "Stein Schere Papier",
    rpsDesc: "Wähle klug",
    round: "Runde",
    youChose: "Du hast gewählt:",
    waitingChoice: "Warte auf Gegner...",
    choose: "Wähle:",
    nextRound: "Nächste Runde",
    // Battleship
    battleship: "Schiffe Versenken",
    battleshipDesc: "Triff alle Schiffe",
    placeFleet: "Platziere deine Flotte",
    confirmFleet: "✅ Flotte bestätigen",
    resetPlacement: "🔄 Neu platzieren",
    horizontal: "→ Horizontal",
    vertical: "↓ Vertikal",
    allPlaced: "✅ Alle Schiffe platziert!",
    waitingEnemy: "Warte auf Gegner...",
    placingShip: "Platziere:",
    fields: "Felder",
    yourFleet: "Deine Flotte",
    enemyField: "Gegnerisches Feld",
    fireNow: "🎯 Du bist dran — schieß!",
    enemyShooting: "schießt...",
    hit: "Treffer",
    miss: "Wasser",
    myShip: "Dein Schiff",
    computer: "Computer",
    poweredBy: "Powered by",
    // ships
    carrier: "Träger",
    battleshipShip: "Schlachtschiff",
    cruiser: "Kreuzer",
    submarine: "U-Boot",
    destroyer: "Zerstörer",
  },
  en: {
    selectGame: "Game Collection",
    enterName: "Enter your name:",
    namePlaceholder: "Your Name",
    nameError: "Please enter your name first!",
    online: "Play Online",
    vsComputer: "vs Computer",
    back: "← Back",
    gameSelection: "← Game Selection",
    startGame: "Start Game",
    createGame: "Create Game",
    loading: "Loading...",
    yourTurn: "Your turn",
    waitingOpponent: "Waiting for opponent...",
    youWin: "You win!",
    draw: "Draw!",
    wins: "wins!",
    rematch: "Rematch",
    newGame: "New Game",
    inviteFriend: "👉 Invite a friend:",
    copyLink: "Copy Link",
    playAs: "You play as",
    spectating: "Spectating...",
    confirmName: "Confirm",
    enterNameFirst: "Please enter your name:",
    tictactoe: "Tic Tac Toe",
    tictactoeDesc: "3 in a row",
    connectFour: "Connect Four",
    connectFourDesc: "4 in a row",
    columnFull: "Column full!",
    rps: "Rock Paper Scissors",
    rpsDesc: "Choose wisely",
    round: "Round",
    youChose: "You chose:",
    waitingChoice: "Waiting for opponent...",
    choose: "Choose:",
    nextRound: "Next Round",
    battleship: "Battleship",
    battleshipDesc: "Sink all ships",
    placeFleet: "Place your fleet",
    confirmFleet: "✅ Confirm Fleet",
    resetPlacement: "🔄 Reset placement",
    horizontal: "→ Horizontal",
    vertical: "↓ Vertical",
    allPlaced: "✅ All ships placed!",
    waitingEnemy: "Waiting for opponent...",
    placingShip: "Placing:",
    fields: "fields",
    yourFleet: "Your Fleet",
    enemyField: "Enemy Field",
    fireNow: "🎯 Your turn — fire!",
    enemyShooting: "is shooting...",
    hit: "Hit",
    miss: "Miss",
    myShip: "Your Ship",
    computer: "Computer",
    poweredBy: "Powered by",
    carrier: "Carrier",
    battleshipShip: "Battleship",
    cruiser: "Cruiser",
    submarine: "Submarine",
    destroyer: "Destroyer",
  },
};

export default lang;
