const lang = {
  de: {
    selectGame: "Spielesammlung",
    enterName: "Gib deinen Namen ein:",
    namePlaceholder: "Dein Name",
    nameError: "Bitte zuerst deinen Namen eingeben!",
    online: "Online spielen",
    vsComputer: "Gegen Computer",
    back: "← Zurück",
    gameSelection: "Spielauswahl",
    startGame: "Spiel starten",
    createGame: "Spiel erstellen",
    loading: "Laden...",
    yourTurn: "Du bist dran",
    waitingOpponent: "Warte auf Mitspieler...",
    youWin: "Du gewinnst!",
    draw: "Unentschieden!",
    wins: "gewinnt!",
    rematch: "Rematch",
    newGame: "Neues Spiel",
    inviteFriend: "Freund einladen",
    copyLink: "Link kopieren",
    playAs: "Du spielst als",
    spectating: "Zuschauer",
    confirmName: "Bestätigen",
    enterNameFirst: "Bitte gib deinen Namen ein:",
    rules: "Regeln",
    closeRules: "Schließen",
    chooseMode: "Spielmodus wählen",
    tictactoe: "Tic Tac Toe",
    tictactoeDesc: "3 in einer Reihe",
    connectFour: "Vier Gewinnt",
    connectFourDesc: "4 in einer Reihe",
    columnFull: "Spalte voll!",
    rps: "Stein Schere Papier",
    rpsDesc: "Wähle klug",
    round: "Runde",
    youChose: "Du hast gewählt:",
    waitingChoice: "Warte auf Gegner...",
    choose: "Wähle deine Waffe:",
    nextRound: "Nächste Runde",
    battleship: "Schiffe Versenken",
    battleshipDesc: "Triff alle Schiffe",
    placeFleet: "Platziere deine Flotte",
    confirmFleet: "Flotte bestätigen",
    resetPlacement: "Neu platzieren",
    rotate: "Drehen (R)",
    horizontal: "Horizontal →",
    vertical: "Vertikal ↓",
    dragToPlace: "Ziehe das Schiff auf das Feld oder klicke",
    dragToReplace: "Platziere das Schiff an neuer Stelle",
    allPlaced: "Alle Schiffe platziert!",
    waitingEnemy: "Warte auf Gegner...",
    placingShip: "Platziere:",
    fields: "Felder",
    yourFleet: "Deine Flotte",
    enemyField: "Gegner angreifen",
    fireNow: "Dein Schuss!",
    enemyShooting: "schießt...",
    hit: "Treffer",
    miss: "Wasser",
    myShip: "Dein Schiff",
    computer: "Computer",
    poweredBy: "Powered by",
    carrier: "Träger",
    battleshipShip: "Schlachtschiff",
    cruiser: "Kreuzer",
    submarine: "U-Boot",
    destroyer: "Zerstörer",
    linkCopied: "Link kopiert!",
    vs: "vs",
    nowShooting: "schießt jetzt",
    yourShotNow: "Du bist dran!",
    turnBanner: "Spielerwechsel",

    // ── Sarcastic win phrases ──
    sarcasticWin: [
      "Nicht schlecht für jemanden, der wahrscheinlich Glück hatte. 😏",
      "Oh wow, du hast gewonnen. Soll ich Konfetti bestellen?",
      "Gratulation. Dein Gegner wird sich bestimmt 'super' fühlen.",
      "Beeindruckend. Fast so beeindruckend wie mein Mittagsschlaf.",
      "Du hast gewonnen! Ich bin... na ja, wenig überrascht.",
      "Schon wieder du? Gönn anderen auch mal was.",
      "Gewonnen! Ich hoffe, das macht deinen Tag. Du wirkst so, als würdest du das brauchen.",
    ],
    sarcasticLoss: [
      "Oh nein. Wie tragisch. Wirklich. 😢",
      "Verloren? Tja. Vielleicht klappt's beim nächsten Mal in 10 Jahren.",
      "Das war... eine mutige Strategie. Mutig und falsch.",
      "Kopf hoch! Schlechter wirst du bestimmt nicht mehr.",
      "Verloren? Keine Sorge, dein Gegner hat sich sicher nicht zu sehr gefreut. Lüge.",
      "Nächstes Mal einfach besser sein. So einfach ist das.",
      "Das war solide. Solide unterirdisch.",
    ],
    sarcasticDraw: [
      "Unentschieden. Keiner gut genug zum Gewinnen. Respekt.",
      "Ein Unentschieden. Das Synonym für 'wir sind beide mittelmäßig'.",
      "Gleichstand! Ihr seid beide gleich... naja.",
      "Remis. Wenn keiner verlieren will, gewinnt auch keiner.",
    ],
    rpsCountdown: ["Stein...", "Schere...", "Papier...", "Los!"],

    reversi: "Reversi",
    reversiDesc: "Umdrehen & Dominieren",
    gomoku: "Gomoku",
    gomokuDesc: "5 in einer Reihe",
    dotsBoxes: "Punkte & Kästchen",
    dotsBoxesDesc: "Verbinde die Punkte",
    memoryMatch: "Memory",
    memoryMatchDesc: "Finde die Paare",
    nim: "Nim",
    nimDesc: "Nimm klug weg",
    mastermind: "Mastermind",
    mastermindDesc: "Knacke den Code",
    yourPieces: "Deine Steine",
    piecesCount: "Steine",
    noValidMoves: "Keine gültigen Züge – Gegner am Zug",
    place: "Setzen",
    lines: "Linien",
    boxes: "Kästchen",
    yourBoxes: "Deine Kästchen",
    pairs: "Paare",
    yourPairs: "Deine Paare",
    flipCard: "Karte aufdecken",
    pile: "Stapel",
    takeStones: "Steine nehmen",
    stonesLeft: "Steine übrig",
    lastStoneLoses: "Wer den letzten Stein nimmt, verliert!",
    setCode: "Code festlegen",
    guess: "Raten",
    codeSet: "Code gesetzt! Gegner rät...",
    attempts: "Versuche",
    attemptsLeft: "Versuche übrig",
    black: "Richtig",
    white: "Fast",
    confirmCode: "Code bestätigen",
    codeBreakerTurn: "Du bist dran – rate den Code!",
    codeSetterWaiting: "Warte auf Rateversuch...",
    codeFound: "Code geknackt!",
    codeNotFound: "Code nicht gefunden!",

    // ── Rules ──
    rulesTitle_tictactoe: "Regeln – Tic Tac Toe",
    rulesTitle_connect4: "Regeln – Vier Gewinnt",
    rulesTitle_rps: "Regeln – Stein Schere Papier",
    rulesTitle_battleship: "Regeln – Schiffe Versenken",
    rules_tictactoe: [
      "Das Spielfeld besteht aus einem 3×3 Raster.",
      "Zwei Spieler setzen abwechselnd ihre Symbole (X und O) in ein freies Feld.",
      "Wer zuerst 3 seiner Symbole in einer Reihe hat (horizontal, vertikal oder diagonal), gewinnt.",
      "Sind alle Felder belegt und niemand hat gewonnen, ist das Spiel unentschieden.",
    ],
    rules_connect4: [
      "Das Spielfeld hat 7 Spalten und 6 Reihen.",
      "Zwei Spieler werfen abwechselnd eine Scheibe in eine Spalte. Die Scheibe fällt auf den tiefsten freien Platz.",
      "Wer zuerst 4 Scheiben in einer Reihe hat (horizontal, vertikal oder diagonal), gewinnt.",
      "Ist das Spielfeld voll ohne Sieger, ist das Spiel unentschieden.",
    ],
    rules_rps: [
      "Beide Spieler wählen gleichzeitig Stein, Schere oder Papier.",
      "Stein schlägt Schere. Schere schlägt Papier. Papier schlägt Stein.",
      "Wählen beide dasselbe, ist die Runde unentschieden.",
      "Der Spieler mit den meisten Runden-Siegen gewinnt die Partie.",
    ],
    rules_battleship: [
      "Jeder Spieler platziert verdeckt eine Flotte aus 5 Schiffen auf einem 10×10 Raster.",
      "Flotte: Träger (5), Schlachtschiff (4), Kreuzer (3), U-Boot (3), Zerstörer (2).",
      "Spieler schießen abwechselnd auf Felder des Gegners.",
      "Trifft ein Schuss ein Schiff, ist es ein Treffer (rot). Verfehlt er, ist es Wasser (blau).",
      "Wer als erster alle Schiffe des Gegners versenkt, gewinnt.",
    ],
    rulesTitle_reversi: "Regeln – Reversi",
    rulesTitle_gomoku: "Regeln – Gomoku",
    rulesTitle_dotsboxes: "Regeln – Punkte & Kästchen",
    rulesTitle_memory: "Regeln – Memory",
    rulesTitle_nim: "Regeln – Nim",
    rulesTitle_mastermind: "Regeln – Mastermind",
    rules_reversi: [
      "Das Spielfeld ist 8×8 Felder groß.",
      "Spieler setzen abwechselnd ihre Steine.",
      "Ein Zug ist gültig, wenn er mindestens einen Gegnerstein einschließt und umdrehen würde.",
      "Alle eingeschlossenen Gegner-Steine werden umgedreht.",
      "Hat ein Spieler keinen gültigen Zug, setzt der Gegner erneut.",
      "Wer am Ende mehr Steine hat, gewinnt.",
    ],
    rules_gomoku: [
      "Das Spielfeld ist 15×15 Felder groß.",
      "Spieler setzen abwechselnd ihre Steine auf freie Felder.",
      "Wer zuerst genau 5 Steine in einer Reihe hat (horizontal, vertikal oder diagonal), gewinnt.",
      "Sechs oder mehr in einer Reihe zählen NICHT.",
      "Sind alle Felder belegt ohne Sieger, ist das Spiel unentschieden.",
    ],
    rules_dotsboxes: [
      "Das Spielfeld besteht aus einem 5×5 Punkt-Raster.",
      "Spieler setzen abwechselnd eine Linie zwischen zwei benachbarte Punkte.",
      "Wer ein Kästchen vervollständigt, erhält einen Punkt und darf nochmal ziehen.",
      "Das Spiel endet, wenn alle Linien gezogen sind.",
      "Wer mehr Kästchen hat, gewinnt.",
    ],
    rules_memory: [
      "16 Karten (8 Paare) liegen verdeckt aus.",
      "Spieler decken abwechselnd 2 Karten auf.",
      "Passen die Karten zusammen, bleiben sie aufgedeckt und der Spieler darf nochmal.",
      "Passen sie nicht, werden sie wieder umgedreht und der Gegner ist dran.",
      "Wer am Ende mehr Paare hat, gewinnt.",
    ],
    rules_nim: [
      "Es gibt 3 Stapel mit 3, 5 und 7 Steinen.",
      "Spieler nehmen abwechselnd beliebig viele Steine von EINEM Stapel.",
      "Man muss mindestens 1 Stein nehmen.",
      "Wer den LETZTEN Stein nimmt, verliert.",
    ],
    rules_mastermind: [
      "Ein Spieler legt einen geheimen 4-Farben-Code fest.",
      "Der andere Spieler hat 10 Versuche, den Code zu erraten.",
      "Nach jedem Versuch gibt es Hinweise: ⚫ = richtige Farbe, richtige Position. ⚪ = richtige Farbe, falsche Position.",
      "Wer den Code knackt, gewinnt. Schafft man es nicht in 10 Versuchen, gewinnt der Code-Setter.",
    ],
  },

  en: {
    selectGame: "Game Collection",
    enterName: "Enter your name:",
    namePlaceholder: "Your Name",
    nameError: "Please enter your name first!",
    online: "Play Online",
    vsComputer: "vs Computer",
    back: "← Back",
    gameSelection: "Game Menu",
    startGame: "Start Game",
    createGame: "Create Game",
    loading: "Loading...",
    yourTurn: "Your turn",
    waitingOpponent: "Waiting for opponent...",
    youWin: "You win!",
    draw: "Draw!",
    wins: "wins!",
    rematch: "Rematch",
    newGame: "New Game",
    inviteFriend: "Invite a friend",
    copyLink: "Copy Link",
    playAs: "You play as",
    spectating: "Spectating",
    confirmName: "Confirm",
    enterNameFirst: "Please enter your name:",
    rules: "Rules",
    closeRules: "Close",
    chooseMode: "Choose Mode",
    tictactoe: "Tic Tac Toe",
    tictactoeDesc: "3 in a row",
    connectFour: "Connect Four",
    connectFourDesc: "4 in a row",
    columnFull: "Column full!",
    rps: "Rock Paper Scissors",
    rpsDesc: "Choose wisely",
    round: "Round",
    youChose: "You chose:",
    waitingChoice: "Waiting for opponent...",
    choose: "Choose your weapon:",
    nextRound: "Next Round",
    battleship: "Battleship",
    battleshipDesc: "Sink all ships",
    placeFleet: "Place your fleet",
    confirmFleet: "Confirm Fleet",
    resetPlacement: "Reset placement",
    rotate: "Rotate (R)",
    horizontal: "Horizontal →",
    vertical: "Vertical ↓",
    dragToPlace: "Drag ship to the grid or click",
    dragToReplace: "Place the ship at a new position",
    allPlaced: "All ships placed!",
    waitingEnemy: "Waiting for opponent...",
    placingShip: "Placing:",
    fields: "cells",
    yourFleet: "Your Fleet",
    enemyField: "Attack",
    fireNow: "Your shot!",
    enemyShooting: "is shooting...",
    hit: "Hit",
    miss: "Miss",
    myShip: "Your Ship",
    computer: "Computer",
    poweredBy: "Powered by",
    carrier: "Carrier",
    battleshipShip: "Battleship",
    cruiser: "Cruiser",
    submarine: "Submarine",
    destroyer: "Destroyer",
    linkCopied: "Link copied!",
    vs: "vs",
    nowShooting: "is shooting now",
    yourShotNow: "Your turn!",
    turnBanner: "Turn Change",

    sarcasticWin: [
      "Not bad for someone who probably just got lucky. 😏",
      "Oh wow, you won. Should I order confetti?",
      "Congrats. Your opponent is definitely feeling 'great' right now.",
      "Impressive. Almost as impressive as my afternoon nap.",
      "You won! I'm... not exactly shocked.",
      "You again? Let others win sometimes.",
      "Victory! I hope this makes your day. You look like you needed it.",
    ],
    sarcasticLoss: [
      "Oh no. How tragic. Really. 😢",
      "Lost? Well. Maybe next time. Like in 10 years.",
      "That was... a brave strategy. Brave and wrong.",
      "Chin up! You probably can't get much worse.",
      "Lost? Don't worry, your opponent barely celebrated. Lie.",
      "Just be better next time. Simple as that.",
      "That was solid. Solidly terrible.",
    ],
    sarcasticDraw: [
      "A draw. Neither good enough to win. Respect.",
      "A tie. Synonym for 'we're both mediocre'.",
      "Equal! You're both equally... well.",
      "Draw. When nobody wants to lose, nobody wins either.",
    ],
    rpsCountdown: ["Rock...", "Scissors...", "Paper...", "Go!"],

    rulesTitle_tictactoe: "Rules – Tic Tac Toe",
    rulesTitle_connect4: "Rules – Connect Four",
    rulesTitle_rps: "Rules – Rock Paper Scissors",
    rulesTitle_battleship: "Rules – Battleship",
    rules_tictactoe: [
      "The board is a 3×3 grid.",
      "Two players take turns placing their symbol (X or O) in an empty cell.",
      "The first player to get 3 in a row (horizontal, vertical, or diagonal) wins.",
      "If all cells are filled with no winner, the game is a draw.",
    ],
    rules_connect4: [
      "The board has 7 columns and 6 rows.",
      "Two players alternate dropping discs into a column. The disc falls to the lowest available space.",
      "The first player to get 4 discs in a row (horizontal, vertical, or diagonal) wins.",
      "If the board fills up with no winner, the game is a draw.",
    ],
    rules_rps: [
      "Both players choose Rock, Scissors, or Paper simultaneously.",
      "Rock beats Scissors. Scissors beats Paper. Paper beats Rock.",
      "If both choose the same, the round is a draw.",
      "The player with the most round wins takes the match.",
    ],
    rules_battleship: [
      "Each player secretly places a fleet of 5 ships on a 10×10 grid.",
      "Fleet: Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2).",
      "Players take turns shooting at cells on the opponent's grid.",
      "A hit turns the cell red; a miss turns it blue.",
      "The first player to sink all of the opponent's ships wins.",
    ],
  },
};

export default lang;
